Replace use of jackson mixin functionality
micronaut-projects/micronaut-problem-json pull request #69
Opened 2021-11-25 16:10 UTC by yawkat

Mixins are not supported by serde. This patch replaces the use of that functionality using a wrapper object before serialization.

2021-11-25 16:44 UTC, graemerocher requested changes

2021-11-25 16:44 UTC, graemerocher commented on problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
> +    static final class ThrowableProblemWithoutStacktrace {
Annotate with `@Introspected` so that an introspection can be used if enabled

2021-11-26 08:53 UTC, graemerocher commented
@sdelamo please take a look

2021-12-02 12:53 UTC, sdelamo requested changes

2021-12-02 12:53 UTC, sdelamo commented on problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
> +    public ProblemErrorResponseProcessor(ProblemConfigurationProperties config) {
Missing javadoc

2021-12-02 12:53 UTC, sdelamo commented on problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
> +    public ProblemErrorResponseProcessor() {
missing javadoc

2021-12-02 12:53 UTC, sdelamo commented on problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
> +    public ProblemErrorResponseProcessor(ProblemConfigurationProperties config) {
this should be `ProblemConfiguration` not `ProblemConfigurationProperties`

2021-12-02 12:53 UTC, sdelamo commented on problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
> +    public ProblemErrorResponseProcessor() {
I've added the javadoc

2021-12-02 12:54 UTC, sdelamo commented on problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
> +    public ProblemErrorResponseProcessor(ProblemConfiguration config) {
I've added the javadoc and change the constructor parameter.

2021-12-02 12:57 UTC, sdelamo commented on problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
> +    public ProblemErrorResponseProcessor(ProblemConfigurationProperties config) {
I've done this change.

2021-12-02 13:23 UTC, sdelamo reviewed
It looks good however, this would be a breaking change.

2021-12-02 13:23 UTC, sdelamo commented on problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
> +public class ProblemErrorResponseProcessor implements ErrorResponseProcessor<Object> {
This would be a breaking change.

2021-12-02 13:23 UTC, sdelamo commented on problem-json/src/main/java/io/micronaut/problem/ProblemErrorResponseProcessor.java
> +    public MutableHttpResponse<Object> processResponse(@NonNull ErrorContext errorContext,
This would be a breaking change.

2021-12-02 14:26 UTC, graemerocher approved these changes

2021-12-02 14:32 UTC, sdelamo approved these changes

2021-12-02 14:33 UTC, merged